### PR TITLE
Added ssh option to avoid printing banner

### PR DESCRIPTION
**Pull request by hkumarmk**

### CODE REVIEW

**Comment by anshprat** [comment]
sigh, doing this *again* via https://github.com/JioCloud/python-jiocloud/pull/67 . Just closing all open PR will reduce our workload I believe.

**Comment by hkumarmk** [comment]
@anshprat What extra you were adding there with 67?

**Comment by anshprat** [comment]
nothing extra. Error needs to be ERROR. ( and I did not know this was open). This needs a rebase hence just closed this.

**Comment by hkumarmk** [comment]
ah okay

**Pull request closed without merging**
