### PR TITLE
Handle connection errors in utils

### PR DESCRIPTION
**Pull request by hkumarmk**
Handling the connection errors with printing the error now.
This will fix the build failures due to connection errors we see now.
On deploy.sh, we can just do a loop to run this until getting a valid ip, may be
after a small sleep of say 5 secs.

### CODE REVIEW

**Comment by hkumarmk** [comment]
This patch is applied in the workspace - /home/jenkins/workspace/puppet-rjil-gate-undercloud of rustedhalo. So this can be tested there.

This is how to reproduce the issue (just need to call server list in parallel).
```
jenkins@jiocloud:~/workspace/puppet-rjil-gate-undercloud$ . venv/bin/activate

(venv)jenkins@jiocloud:~/workspace/puppet-rjil-gate-undercloud$ for i in `seq 5`; do python -m jiocloud.utils get_ip_of_node uc1_testjenkins-puppet-rjil-gate-undercloud-65 & done
[1] 22963
[2] 22964
[3] 22965
[4] 22966
[5] 22967
(venv)jenkins@jiocloud:~/workspace/puppet-rjil-gate-undercloud$ s=`python -m jiocloud.utils get_ip_of_node uc1_testjenkins-puppet-rjil-gate-undercloud-65`

Failed on nova list ('Connection aborted.', BadStatusLine("''",))

Failed on nova list ('Connection aborted.', BadStatusLine("''",))

Failed on nova list ('Connection aborted.', BadStatusLine("''",))

Failed on nova list ('Connection aborted.', BadStatusLine("''",))

Failed on nova list ('Connection aborted.', BadStatusLine("''",))

Failed on nova list ('Connection aborted.', BadStatusLine("''",))
[1]   Done                    python -m jiocloud.utils get_ip_of_node uc1_testjenkins-puppet-rjil-gate-undercloud-65
[2]   Done                    python -m jiocloud.utils get_ip_of_node uc1_testjenkins-puppet-rjil-gate-undercloud-65
[3]   Done                    python -m jiocloud.utils get_ip_of_node uc1_testjenkins-puppet-rjil-gate-undercloud-65
[4]-  Done                    python -m jiocloud.utils get_ip_of_node uc1_testjenkins-puppet-rjil-gate-undercloud-65
[5]+  Done                    python -m jiocloud.utils get_ip_of_node uc1_testjenkins-puppet-rjil-gate-undercloud-65
(venv)jenkins@jiocloud:~/workspace/puppet-rjil-gate-undercloud$ 
(venv)jenkins@jiocloud:~/workspace/puppet-rjil-gate-undercloud$ echo $s
```

**Comment by anshprat** [comment]
@hkumarmk so we are only handling the exception correct? Calling it again is left to the original caller?

**Comment by hkumarmk** [comment]
This is already there in deploy.sh

**Comment by anshprat** [comment]
ok, looking good. Merging.

**Comment by hkumarmk** [comment]
im going to update this in the workspaces of jenkins

**Pull request merged**
